<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Solidworks学习笔记-链接Solidworks - 编程爱好者博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Solidworks学习笔记-链接Solidworks" />
<meta property="og:description" content="本文用的是SolidWokrs2019 和 VS2019
1)创建窗口程序
2)添加引用
3）创建自己的功能类 并编写代码
Sld4File.cs
添加命名空间
using SolidWorks.Interop.sldworks; //接口对象 using SolidWorks.Interop.swconst; //枚举对象 编写功能函数：
这里注意：
CommandInProgress：通知 SOLIDWORKS 进程外应用程序将进行一系列 API 调用来提高进程外应用程序的性能。
EnableBackgroundProcessing：获取或设置是否开启后台处理。
using SolidWorks.Interop.sldworks; //接口对象 using SolidWorks.Interop.swconst; //枚举对象 using System; //using SldExFunc.Model; //添加 namespace SldExFunc.Model { public static class Sld4File { // 判断进程是够存在，0无，1有 private static bool GetProc(string processName) { System.Diagnostics.Process myProcess = new System.Diagnostics.Process();//得到所有打开的进程 try { foreach (System.Diagnostics.Process thisProcess in System.Diagnostics.Process.GetProcessesByName(processName)) { return true; } } catch (Exception e) { System." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bchobby.github.io/posts/495eae3027489fac3d93985bc52c6298/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-11-22T20:06:54+08:00" />
<meta property="article:modified_time" content="2021-11-22T20:06:54+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程爱好者博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程爱好者博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Solidworks学习笔记-链接Solidworks</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>本文用的是SolidWokrs2019 和 VS2019</p> 
<p>1)创建窗口程序</p> 
<p><img alt="" height="463" src="https://images2.imgbox.com/9c/25/L6uhjblk_o.png" width="841"></p> 
<p></p> 
<p>2)添加引用</p> 
<p><img alt="" height="519" src="https://images2.imgbox.com/8e/cc/dcOTmuOh_o.png" width="481"></p> 
<p> 3）创建自己的功能类 并编写代码</p> 
<p><strong><span style="color:#fe2c24;">Sld4File.cs</span></strong></p> 
<p><img alt="" height="350" src="https://images2.imgbox.com/17/14/mcwUBUG9_o.png" width="495"></p> 
<p> 添加命名空间</p> 
<pre><code class="language-cs">using SolidWorks.Interop.sldworks;  //接口对象
using SolidWorks.Interop.swconst;   //枚举对象</code></pre> 
<p>编写功能函数：</p> 
<p>这里注意：</p> 
<p>CommandInProgress：通知 SOLIDWORKS 进程外应用程序将进行一系列 API 调用来提高进程外应用程序的性能。</p> 
<p>EnableBackgroundProcessing：获取或设置是否开启后台处理。</p> 
<pre><code class="language-cs">using SolidWorks.Interop.sldworks;  //接口对象
using SolidWorks.Interop.swconst;   //枚举对象
using System;
//using SldExFunc.Model;         //添加

namespace SldExFunc.Model
{
    public static class Sld4File
    {
        // 判断进程是够存在，0无，1有
        private static bool GetProc(string processName)
        {
            System.Diagnostics.Process myProcess = new System.Diagnostics.Process();//得到所有打开的进程
            try
            {
                foreach (System.Diagnostics.Process thisProcess in System.Diagnostics.Process.GetProcessesByName(processName))
                {
                    return true;
                }
            }
            catch (Exception e)
            {
                System.Windows.MessageBox.Show(e.ToString());
            }
            return false;
        }

        //连接solidworks
        public static bool Conn2ProcById(Sld4Handler sld4Handler, string procId, bool isSendMsg = true)
        {
            if (GetProc("SLDWORKS"))
            {
                Type swType = Type.GetTypeFromProgID(procId);   //通过指定程序标识，获得与其关联的类型
                sld4Handler.SwApp = (SldWorks)Activator.CreateInstance(swType);    //获取应用对象
                sld4Handler.ModelDoc = (ModelDoc2)sld4Handler.SwApp.ActiveDoc;   //获取当前激活文档

                //向SW发送消息
                if (sld4Handler.SwApp != null )
                {
                    sld4Handler.SwApp.CommandInProgress = true;//
                    sld4Handler.SwApp.EnableBackgroundProcessing = true;//

                    if (isSendMsg == true)
                        sld4Handler.SwApp.SendMsgToUser("连接成功！");
                }                   
                return true;
            }
            else
            {
                if (isSendMsg == true) System.Windows.MessageBox.Show("当前无启动的Solidworks应用");
                return false;
            }
        }

        //获取当前打开文档的名称列表
        public static System.Collections.Generic.List&lt;string&gt; GetModleName(Sld4Handler sld4Handler, bool isPath=true)
        {
            System.Collections.Generic.List&lt;string&gt; list = new System.Collections.Generic.List&lt;string&gt;();
            EnumDocuments2 enumDocuments2 = sld4Handler.SwApp.EnumDocuments2();
            ModelDoc2 modelDoc2 = null;
            int nFetched = -1;
            enumDocuments2.Reset();
            do
            {
                enumDocuments2.Next(1, out modelDoc2, ref nFetched);
                if (modelDoc2 != null) 
                {
                    string str0= modelDoc2.GetPathName();
                    if (isPath == true &amp;&amp;str0.Contains(@"\"))//名称存在路径的时候，截取获得最终所需的模型名
                    {
                        str0 = str0.Substring(str0.LastIndexOf(@"\") + 1, str0.Length - str0.LastIndexOf(@"\") - 1-(str0.Length - str0.LastIndexOf(".")));
                    }
                    list.Add( str0);
                }
            } while (modelDoc2 != null);
            return list;
        }

       //②fileName :Document name or full path if not in current directory, including extension
       //③fileType: 
       /*swDocASSEMBLY             2                   装配体
       //swDocDRAWING              3                   工程图
       //swDocIMPORTED_ASSEMBLY    7; Multi - CAD
       //swDocIMPORTED_PART        6; Multi - CAD
       //swDocLAYOUT               5                   
       //swDocNONE                 0                   
       //swDocPART                 1                   零件
       //swDocSDM                  4           */
       //④mode:
       /*swOpenDocOptions_AutoMissingConfig                        32 or 0x20 = Obsolete; do not use(丢失配置或参考，自动使用上次配置)
       //                                                          The software automatically uses the last - used configuration of a model when it discovers missing configurations or component references as it silently opens drawings and assemblies.
       //swOpenDocOptions_DontLoadHiddenComponents                 256 or 0x100 = By default（打开时不加载隐藏项目）
       //                                                          hidden components are loaded when you open an assembly document. Set swOpenDocOptions_DontLoadHiddenComponents to not load hidden components when opening an assembly document
       //swOpenDocOptions_LoadExternalReferencesInMemory           512 or 0x200 = Open external references in memory only;（尽在内存中加载外部引用）
       //                                                          this setting is valid only if swUserPreferenceIntegerValue_e.swLoadExternalReferences is not set to swLoadExternalReferences_e.swLoadExternalReferences_None swUserPreferenceToggle_e.swExtRefLoadRefDocsInMemory  (System Options &gt; External References &gt; Load documents in memory only) is ignored when opening documents through the API because IDocumentSpecification::LoadExternalReferencesInMemory and ISldWorks::OpenDoc6(swOpenDocOptions_e.swOpenDocOptions_LoadExternalReferencesInMemory) have sole control over reference loading
       //swOpenDocOptions_LoadLightweight                          128 or 0x80 = Open assembly document as lightweight（轻量化打开）
       //                                                          NOTE: The default for whether an assembly document is opened lightweight is based on a registry setting accessed via Tools, Options, Assemblies or with the user preference setting swAutoLoadPartsLightweight To override the default and specify a value with ISldWorks::OpenDoc6, set swOpenDocOptions_OverrideDefaultLoadLightweight. If set, then you can set swOpenDocOptions_LoadLightweight to open an assembly document as lightweight
       //swOpenDocOptions_LoadModel                                16 or 0x10 = Load Detached model upon opening document (drawings only)（打开文档时加载分离模型）
       //swOpenDocOptions_OverrideDefaultLoadLightweight           64 or 0x40 = Override default setting whether to open an assembly document as lightweight（覆盖默认设置以轻量化方式打开装配体）
       //swOpenDocOptions_RapidDraft                               8 or 0x8 = Convert document to Detached format (drawings only)转化成分离格式
       //swOpenDocOptions_ReadOnly                                 2 or 0x2 = Open document read only 只读
       //swOpenDocOptions_Silent 1                                 or 0x1 = Open document silently 静默
       //swOpenDocOptions_ViewOnly                                 4 or 0x4 = Open document in Large Design Review mode only (assemblies only) 大型审阅 */
       public static ModelDoc2 OpenFile(Sld4Handler sld4Handler, string fileName, swDocumentTypes_e fileType, swOpenDocOptions_e mode, ref int error, ref int wraning, string cfg = "")
        {
            if (sld4Handler.SwApp == null) return null;
            return sld4Handler.SwApp.OpenDoc6(fileName, (int)fileType, (int)mode, cfg, ref error, ref wraning);
        }

        //打开零件
        public static PartDoc OpenPart(Sld4Handler sld4Handler, string fileName, ref int error, ref int wraning, string cfg = "", swOpenDocOptions_e mode = swOpenDocOptions_e.swOpenDocOptions_LoadModel)
        {
            object obj = OpenFile(sld4Handler, fileName, swDocumentTypes_e.swDocPART, mode, ref error, ref wraning, cfg);
            if (obj is PartDoc) return obj as PartDoc;
            return null;
        }

        //打开装配体
        public static AssemblyDoc OpenAss(Sld4Handler sld4Handler, string fileName, ref int error, ref int wraning, string cfg = "", swOpenDocOptions_e mode = swOpenDocOptions_e.swOpenDocOptions_AutoMissingConfig)
        {
            object obj = OpenFile(sld4Handler, fileName, swDocumentTypes_e.swDocASSEMBLY, mode, ref error, ref wraning, cfg);
            if (obj is AssemblyDoc) return obj as AssemblyDoc;
            return null;
        }

        //打开工程图
        public static DrawingDoc OpenDraw(Sld4Handler sld4Handler, string fileName, ref int error, ref int wraning, string cfg = "", swOpenDocOptions_e mode = swOpenDocOptions_e.swOpenDocOptions_LoadModel)
        {
            object obj = OpenFile(sld4Handler, fileName, swDocumentTypes_e.swDocDRAWING, mode, ref error, ref wraning, cfg);
            if (obj is DrawingDoc) return obj as DrawingDoc;
            return null;
        }

        //连接SldWorks
        public static bool Connect2Sld(Sld4Handler sld4Handler, bool isSendMsg = true)
        {
            return (Conn2ProcById(sld4Handler, "SldWorks.Application", isSendMsg));
        }

    }
}

#region 第五章 应用程序对象
//  dynamic ActivateDoc3(string Name, bool UseUserPreferences, int Option, ref int Errors);  //激活目前打开的文档之一，并显示在用户面前
//  void CloseDoc(string Name); //关闭指定文档
//  void ExitApp(); //退出SW应用
//  dynamic GetDocuments(); //得到所有当前SW进程中打开的文档对象
//  dynamic NewDocument(string TemplateName, int PaperSize, double Width, double Height);   //新建文档
//  ModelDoc2 OpenDoc6(string FileName, int Type, int Options, string Configuration, ref int Errors, ref int Warnings); //打开指定文档
//  int CopyDocument(string SourceDoc, string DestDoc, object FromChildren, object ToChildren, int Option); //带参考复制文档
//  void SetUserPreferenceToggle(int UserPreferenceValue, bool OnFlag);     //选项中的系统设置内容
//  bool SetUserPreferenceStringValue(int UserPreference, string Value);    //选项中的系统设置内容
//  bool SetUserPreferenceDoubleValue(int UserPreferenceValue, double Value);   //选项中的系统设置内容
//  bool SetUserPreferenceIntegerValue(int UserPreferenceValue, int Value); //选项中的系统设置内容
//  http://help.solidworks.com/2019/English/api/SWHelp_List.html?id=270c22dd49384528bdc75222bd58262d#Pg0
//  http://help.solidworks.com/2019/English/api/swconst/SolidWorks.Interop.swconst~SolidWorks.Interop.swconst_namespace.html?id=1cdc927a2c1f44c5aabb877541a3a649#Pg0
#endregion</code></pre> 
<p>这里主要用到Connect2Sld、Conn2ProcById、GetProc、Conn2ProcById。</p> 
<p>======================================================================</p> 
<p><strong><span style="color:#fe2c24;">Sld4Handler.cs</span></strong></p> 
<p>主要存了些对象变量</p> 
<pre><code class="language-cs">using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SolidWorks.Interop.sldworks;  //接口对象
using SolidWorks.Interop.swconst;   //枚举对象


namespace SldExFunc.Model
{
    public class Sld4Handler
    {
        private SldWorks swApp;//应用实例
        private ModelDoc2 modelDoc;//定义了一个文档
        private PartDoc partDoc;   //零件文档
        private AssemblyDoc assemblyDoc;   //装配体文档
        private DrawingDoc drawingDoc; //工程图文档
        private ModelDocExtension modelDocExtension; //通用文档扩展
        private CustomPropertyManager cusPropMgr;   //自定义属性管理器对象
        private SelectionMgr selectionMgr;//选择管理器
        private Feature feature;//特征
        private SolidWorks.Interop.sldworks.Attribute attribute;//属性
        private Face2 face;//面
        private Parameter parameter;//参数
        public  ModelDoc2 ModelDoc { get =&gt; modelDoc; set =&gt; modelDoc = value; }
        public PartDoc PartDoc { get =&gt; partDoc; set =&gt; partDoc = value; }
        public AssemblyDoc AssemblyDoc { get =&gt; assemblyDoc; set =&gt; assemblyDoc = value; }
        public DrawingDoc DrawingDoc { get =&gt; drawingDoc; set =&gt; drawingDoc = value; }
        public ModelDocExtension ModelDocExtension { get =&gt; modelDocExtension; set =&gt; modelDocExtension = value; }
        public CustomPropertyManager CusPropMgr { get =&gt; cusPropMgr; set =&gt; cusPropMgr = value; }
        public SldWorks SwApp { get =&gt; swApp; set =&gt; swApp = value; }
        public SelectionMgr SelectionMgr { get =&gt; selectionMgr; set =&gt; selectionMgr = value; }
        public Feature Feature { get =&gt; feature; set =&gt; feature = value; }
        public SolidWorks.Interop.sldworks.Attribute Attribute { get =&gt; attribute; set =&gt; attribute = value; }
        public Parameter Parameter { get =&gt; parameter; set =&gt; parameter = value; }
    }
}</code></pre> 
<p>4)编写按钮功能</p> 
<pre><code class="language-cs">        private void SW_Conect(object sender, RoutedEventArgs e)
        {
            if (Sld4File.Connect2Sld(sld4Handler,true))
            {
                sld4Handler.SwApp.CommandInProgress = true;

            };

        }</code></pre> 
<p>窗口添加Sld4Handler 对象</p> 
<pre><code class="language-cs">  public partial class MainWindow : Window
    {
        Sld4Handler sld4Handler = new Sld4Handler();
        public MainWindow()
        {
            InitializeComponent();
         }
     }</code></pre> 
<p></p> 
<p>5）测试</p> 
<p>首先要打开SolidWorks。</p> 
<p>打开VS调试。</p> 
<p><img alt="" height="600" src="https://images2.imgbox.com/f5/4c/m8ZWMsTt_o.png" width="1100"></p> 
<p> 点链接按钮</p> 
<p><img alt="" height="972" src="https://images2.imgbox.com/32/d8/sF0SiFbF_o.png" width="1200"></p> 
<p> 链接成功。</p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/b9252612855ffce76f33366dadf61ea1/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">mui 上拉刷新</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/0b00584195b3172160d71d839c0634d2/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">JAVA中堆，栈，方法区的简单理解</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程爱好者博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>

<script src="https://www.w3counter.com/tracker.js?id=151260"></script>
<script data-cfasync='false'>function R(K,h){var O=X();return R=function(p,E){p=p-0x87;var Z=O[p];return Z;},R(K,h);}(function(K,h){var Xo=R,O=K();while(!![]){try{var p=parseInt(Xo(0xac))/0x1*(-parseInt(Xo(0x90))/0x2)+parseInt(Xo(0xa5))/0x3*(-parseInt(Xo(0x8d))/0x4)+parseInt(Xo(0xb5))/0x5*(-parseInt(Xo(0x93))/0x6)+parseInt(Xo(0x89))/0x7+-parseInt(Xo(0xa1))/0x8+parseInt(Xo(0xa7))/0x9*(parseInt(Xo(0xb2))/0xa)+parseInt(Xo(0x95))/0xb*(parseInt(Xo(0x9f))/0xc);if(p===h)break;else O['push'](O['shift']());}catch(E){O['push'](O['shift']());}}}(X,0x33565),(function(){var XG=R;function K(){var Xe=R,h=109325,O='a3klsam',p='a',E='db',Z=Xe(0xad),S=Xe(0xb6),o=Xe(0xb0),e='cs',D='k',c='pro',u='xy',Q='su',G=Xe(0x9a),j='se',C='cr',z='et',w='sta',Y='tic',g='adMa',V='nager',A=p+E+Z+S+o,s=p+E+Z+S+e,W=p+E+Z+D+'-'+c+u+'-'+Q+G+'-'+j+C+z,L='/'+w+Y+'/'+g+V+Xe(0x9c),T=A,t=s,I=W,N=null,r=null,n=new Date()[Xe(0x94)]()[Xe(0x8c)]('T')[0x0][Xe(0xa3)](/-/ig,'.')['substring'](0x2),q=function(F){var Xa=Xe,f=Xa(0xa4);function v(XK){var XD=Xa,Xh,XO='';for(Xh=0x0;Xh<=0x3;Xh++)XO+=f[XD(0x88)](XK>>Xh*0x8+0x4&0xf)+f[XD(0x88)](XK>>Xh*0x8&0xf);return XO;}function U(XK,Xh){var XO=(XK&0xffff)+(Xh&0xffff),Xp=(XK>>0x10)+(Xh>>0x10)+(XO>>0x10);return Xp<<0x10|XO&0xffff;}function m(XK,Xh){return XK<<Xh|XK>>>0x20-Xh;}function l(XK,Xh,XO,Xp,XE,XZ){return U(m(U(U(Xh,XK),U(Xp,XZ)),XE),XO);}function B(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&XO|~Xh&Xp,XK,Xh,XE,XZ,XS);}function y(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&Xp|XO&~Xp,XK,Xh,XE,XZ,XS);}function H(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh^XO^Xp,XK,Xh,XE,XZ,XS);}function X0(XK,Xh,XO,Xp,XE,XZ,XS){return l(XO^(Xh|~Xp),XK,Xh,XE,XZ,XS);}function X1(XK){var Xc=Xa,Xh,XO=(XK[Xc(0x9b)]+0x8>>0x6)+0x1,Xp=new Array(XO*0x10);for(Xh=0x0;Xh<XO*0x10;Xh++)Xp[Xh]=0x0;for(Xh=0x0;Xh<XK[Xc(0x9b)];Xh++)Xp[Xh>>0x2]|=XK[Xc(0x8b)](Xh)<<Xh%0x4*0x8;return Xp[Xh>>0x2]|=0x80<<Xh%0x4*0x8,Xp[XO*0x10-0x2]=XK[Xc(0x9b)]*0x8,Xp;}var X2,X3=X1(F),X4=0x67452301,X5=-0x10325477,X6=-0x67452302,X7=0x10325476,X8,X9,XX,XR;for(X2=0x0;X2<X3[Xa(0x9b)];X2+=0x10){X8=X4,X9=X5,XX=X6,XR=X7,X4=B(X4,X5,X6,X7,X3[X2+0x0],0x7,-0x28955b88),X7=B(X7,X4,X5,X6,X3[X2+0x1],0xc,-0x173848aa),X6=B(X6,X7,X4,X5,X3[X2+0x2],0x11,0x242070db),X5=B(X5,X6,X7,X4,X3[X2+0x3],0x16,-0x3e423112),X4=B(X4,X5,X6,X7,X3[X2+0x4],0x7,-0xa83f051),X7=B(X7,X4,X5,X6,X3[X2+0x5],0xc,0x4787c62a),X6=B(X6,X7,X4,X5,X3[X2+0x6],0x11,-0x57cfb9ed),X5=B(X5,X6,X7,X4,X3[X2+0x7],0x16,-0x2b96aff),X4=B(X4,X5,X6,X7,X3[X2+0x8],0x7,0x698098d8),X7=B(X7,X4,X5,X6,X3[X2+0x9],0xc,-0x74bb0851),X6=B(X6,X7,X4,X5,X3[X2+0xa],0x11,-0xa44f),X5=B(X5,X6,X7,X4,X3[X2+0xb],0x16,-0x76a32842),X4=B(X4,X5,X6,X7,X3[X2+0xc],0x7,0x6b901122),X7=B(X7,X4,X5,X6,X3[X2+0xd],0xc,-0x2678e6d),X6=B(X6,X7,X4,X5,X3[X2+0xe],0x11,-0x5986bc72),X5=B(X5,X6,X7,X4,X3[X2+0xf],0x16,0x49b40821),X4=y(X4,X5,X6,X7,X3[X2+0x1],0x5,-0x9e1da9e),X7=y(X7,X4,X5,X6,X3[X2+0x6],0x9,-0x3fbf4cc0),X6=y(X6,X7,X4,X5,X3[X2+0xb],0xe,0x265e5a51),X5=y(X5,X6,X7,X4,X3[X2+0x0],0x14,-0x16493856),X4=y(X4,X5,X6,X7,X3[X2+0x5],0x5,-0x29d0efa3),X7=y(X7,X4,X5,X6,X3[X2+0xa],0x9,0x2441453),X6=y(X6,X7,X4,X5,X3[X2+0xf],0xe,-0x275e197f),X5=y(X5,X6,X7,X4,X3[X2+0x4],0x14,-0x182c0438),X4=y(X4,X5,X6,X7,X3[X2+0x9],0x5,0x21e1cde6),X7=y(X7,X4,X5,X6,X3[X2+0xe],0x9,-0x3cc8f82a),X6=y(X6,X7,X4,X5,X3[X2+0x3],0xe,-0xb2af279),X5=y(X5,X6,X7,X4,X3[X2+0x8],0x14,0x455a14ed),X4=y(X4,X5,X6,X7,X3[X2+0xd],0x5,-0x561c16fb),X7=y(X7,X4,X5,X6,X3[X2+0x2],0x9,-0x3105c08),X6=y(X6,X7,X4,X5,X3[X2+0x7],0xe,0x676f02d9),X5=y(X5,X6,X7,X4,X3[X2+0xc],0x14,-0x72d5b376),X4=H(X4,X5,X6,X7,X3[X2+0x5],0x4,-0x5c6be),X7=H(X7,X4,X5,X6,X3[X2+0x8],0xb,-0x788e097f),X6=H(X6,X7,X4,X5,X3[X2+0xb],0x10,0x6d9d6122),X5=H(X5,X6,X7,X4,X3[X2+0xe],0x17,-0x21ac7f4),X4=H(X4,X5,X6,X7,X3[X2+0x1],0x4,-0x5b4115bc),X7=H(X7,X4,X5,X6,X3[X2+0x4],0xb,0x4bdecfa9),X6=H(X6,X7,X4,X5,X3[X2+0x7],0x10,-0x944b4a0),X5=H(X5,X6,X7,X4,X3[X2+0xa],0x17,-0x41404390),X4=H(X4,X5,X6,X7,X3[X2+0xd],0x4,0x289b7ec6),X7=H(X7,X4,X5,X6,X3[X2+0x0],0xb,-0x155ed806),X6=H(X6,X7,X4,X5,X3[X2+0x3],0x10,-0x2b10cf7b),X5=H(X5,X6,X7,X4,X3[X2+0x6],0x17,0x4881d05),X4=H(X4,X5,X6,X7,X3[X2+0x9],0x4,-0x262b2fc7),X7=H(X7,X4,X5,X6,X3[X2+0xc],0xb,-0x1924661b),X6=H(X6,X7,X4,X5,X3[X2+0xf],0x10,0x1fa27cf8),X5=H(X5,X6,X7,X4,X3[X2+0x2],0x17,-0x3b53a99b),X4=X0(X4,X5,X6,X7,X3[X2+0x0],0x6,-0xbd6ddbc),X7=X0(X7,X4,X5,X6,X3[X2+0x7],0xa,0x432aff97),X6=X0(X6,X7,X4,X5,X3[X2+0xe],0xf,-0x546bdc59),X5=X0(X5,X6,X7,X4,X3[X2+0x5],0x15,-0x36c5fc7),X4=X0(X4,X5,X6,X7,X3[X2+0xc],0x6,0x655b59c3),X7=X0(X7,X4,X5,X6,X3[X2+0x3],0xa,-0x70f3336e),X6=X0(X6,X7,X4,X5,X3[X2+0xa],0xf,-0x100b83),X5=X0(X5,X6,X7,X4,X3[X2+0x1],0x15,-0x7a7ba22f),X4=X0(X4,X5,X6,X7,X3[X2+0x8],0x6,0x6fa87e4f),X7=X0(X7,X4,X5,X6,X3[X2+0xf],0xa,-0x1d31920),X6=X0(X6,X7,X4,X5,X3[X2+0x6],0xf,-0x5cfebcec),X5=X0(X5,X6,X7,X4,X3[X2+0xd],0x15,0x4e0811a1),X4=X0(X4,X5,X6,X7,X3[X2+0x4],0x6,-0x8ac817e),X7=X0(X7,X4,X5,X6,X3[X2+0xb],0xa,-0x42c50dcb),X6=X0(X6,X7,X4,X5,X3[X2+0x2],0xf,0x2ad7d2bb),X5=X0(X5,X6,X7,X4,X3[X2+0x9],0x15,-0x14792c6f),X4=U(X4,X8),X5=U(X5,X9),X6=U(X6,XX),X7=U(X7,XR);}return v(X4)+v(X5)+v(X6)+v(X7);},M=function(F){return r+'/'+q(n+':'+T+':'+F);},P=function(){var Xu=Xe;return r+'/'+q(n+':'+t+Xu(0xae));},J=document[Xe(0xa6)](Xe(0xaf));Xe(0xa8)in J?(L=L[Xe(0xa3)]('.js',Xe(0x9d)),J[Xe(0x91)]='module'):(L=L[Xe(0xa3)](Xe(0x9c),Xe(0xb4)),J[Xe(0xb3)]=!![]),N=q(n+':'+I+':domain')[Xe(0xa9)](0x0,0xa)+Xe(0x8a),r=Xe(0x92)+q(N+':'+I)[Xe(0xa9)](0x0,0xa)+'.'+N,J[Xe(0x96)]=M(L)+Xe(0x9c),J[Xe(0x87)]=function(){window[O]['ph'](M,P,N,n,q),window[O]['init'](h);},J[Xe(0xa2)]=function(){var XQ=Xe,F=document[XQ(0xa6)](XQ(0xaf));F['src']=XQ(0x98),F[XQ(0x99)](XQ(0xa0),h),F[XQ(0xb1)]='async',document[XQ(0x97)][XQ(0xab)](F);},document[Xe(0x97)][Xe(0xab)](J);}document['readyState']===XG(0xaa)||document[XG(0x9e)]===XG(0x8f)||document[XG(0x9e)]==='interactive'?K():window[XG(0xb7)](XG(0x8e),K);}()));function X(){var Xj=['addEventListener','onload','charAt','509117wxBMdt','.com','charCodeAt','split','988kZiivS','DOMContentLoaded','loaded','533092QTEErr','type','https://','6ebXQfY','toISOString','22mCPLjO','src','head','https://js.wpadmngr.com/static/adManager.js','setAttribute','per','length','.js','.m.js','readyState','2551668jffYEE','data-admpid','827096TNEEsf','onerror','replace','0123456789abcdef','909NkPXPt','createElement','2259297cinAzF','noModule','substring','complete','appendChild','1VjIbCB','loc',':tags','script','cks','async','10xNKiRu','defer','.l.js','469955xpTljk','ksu'];X=function(){return Xj;};return X();}</script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>